# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a522d6855d138a306cbac9e6c3edcd7727d2e8477c3fa67bab0959e49fd57a38baef864784e8c74b9f99190e33561861a79f40c31045e23e9030f8487eb959

test:
  secret_key_base: bee881158175e34959b792ccc546978254bbd345a144102e1fbc4f8be9b8ae82f31c29ead50ea5c7acea814f2c58a4d7a90ea79e63293b838ec5dc367d2bfd05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
